import os
import argparse
from tqdm import tqdm

import torch
import torch.nn as nn
import numpy as np
import wandb

from t5_utils import initialize_model, initialize_optimizer_and_scheduler, save_model, load_model_from_checkpoint, setup_wandb
from transformers import GenerationConfig
from load_data import load_t5_data, T5_TOKENIZER 
from utils import compute_metrics, save_queries_and_records

DEVICE = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
PAD_IDX = 0

def get_args():
    '''
    Arguments for training.
    '''
    parser = argparse.ArgumentParser(description='T5 training loop')

    # Model hyperparameters
    parser.add_argument('--finetune', action='store_true', help="Whether to finetune T5 or not")
    
    # Training hyperparameters
    parser.add_argument('--optimizer_type', type=str, default="AdamW", choices=["AdamW"],
                        help="What optimizer to use")
    parser.add_argument('--learning_rate', type=float, default=5e-5) # Changed default to safer 5e-5
    parser.add_argument('--weight_decay', type=float, default=0.01)

    parser.add_argument('--scheduler_type', type=str, default="cosine", choices=["none", "cosine", "linear"],
                        help="Whether to use a LR scheduler and what type to use if so")
    parser.add_argument('--num_warmup_epochs', type=int, default=5, # Increased warmup
                        help="How many epochs to warm up the learning rate for if using a scheduler")
    parser.add_argument('--max_n_epochs', type=int, default=100,
                        help="How many epochs to train the model for")
    parser.add_argument('--patience_epochs', type=int, default=10,
                        help="If validation performance stops improving, how many epochs should we wait before stopping?")

    parser.add_argument('--use_wandb', action='store_true',
                        help="If set, we will use wandb to keep track of experiments")
    parser.add_argument('--experiment_name', type=str, default='experiment',
                        help="How should we name this experiment?")

    # Data hyperparameters
    parser.add_argument('--batch_size', type=int, default=16)
    parser.add_argument('--test_batch_size', type=int, default=16)

    args = parser.parse_args()
    return args

def clean_sql_query(query):
    """
    Simple heuristics to fix common syntax errors generated by T5.
    This helps improve F1 by rescuing 'almost correct' queries.
    """
    # Fix 1: Unbalanced parentheses
    open_parens = query.count('(')
    close_parens = query.count(')')
    if open_parens > close_parens:
        query += ')' * (open_parens - close_parens)
        
    # Fix 2: Unbalanced quotes
    if query.count("'") % 2 != 0:
        query += "'"
        
    # Fix 3: Remove trailing "AND" or "WHERE" if the model stopped early
    query = query.strip()
    if query.endswith(" AND"):
        query = query[:-4]
    if query.endswith(" WHERE"):
        query = query[:-6]
        
    return query

def train(args, model, tokenizer, train_loader, dev_loader, optimizer, scheduler):
    best_f1 = -1
    epochs_since_improvement = 0

    model_type = 'ft' if args.finetune else 'scr'
    checkpoint_dir = os.path.join('checkpoints', f'{model_type}_experiments', args.experiment_name)
    os.makedirs(checkpoint_dir, exist_ok=True)
    args.checkpoint_dir = checkpoint_dir
    experiment_name = 'ft_experiment'
    
    gt_sql_path = os.path.join(f'data/dev.sql')
    
    # *** FIX: Point to the correct pre-computed record file to speed up eval ***
    gt_record_path = os.path.join(f'records/ground_truth_dev.pkl')
    
    model_sql_path = os.path.join(f'results/t5_{model_type}_{experiment_name}_dev.sql')
    model_record_path = os.path.join(f'records/t5_{model_type}_{experiment_name}_dev.pkl')
    
    for epoch in range(args.max_n_epochs):
        tr_loss = train_epoch(args, model, train_loader, optimizer, scheduler)
        print(f"Epoch {epoch}: Average train loss was {tr_loss}")

        eval_loss, record_f1, record_em, sql_em, error_rate = eval_epoch(
            args, model, tokenizer, dev_loader,
            gt_sql_path, model_sql_path,
            gt_record_path, model_record_path
        )
        print(f"Epoch {epoch}: Dev loss: {eval_loss}, Record F1: {record_f1}, Record EM: {record_em}, SQL EM: {sql_em}")
        print(f"Epoch {epoch}: {error_rate*100:.2f}% of the generated outputs led to SQL errors")

        if args.use_wandb:
            result_dict = {
                'train/loss' : tr_loss,
                'dev/loss' : eval_loss,
                'dev/record_f1' : record_f1,
                'dev/record_em' : record_em,
                'dev/sql_em' : sql_em,
                'dev/error_rate' : error_rate,
            }
            wandb.log(result_dict, step=epoch)

        if record_f1 > best_f1:
            best_f1 = record_f1
            epochs_since_improvement = 0
            print(f"New best F1: {best_f1}. Saving model.")
            save_model(checkpoint_dir, model, best=True)
        else:
            epochs_since_improvement += 1
            print(f"No improvement in {epochs_since_improvement} epochs.")

        save_model(checkpoint_dir, model, best=False)

        if epochs_since_improvement >= args.patience_epochs:
            print(f"Stopping early after {args.patience_epochs} epochs.")
            break

def train_epoch(args, model, train_loader, optimizer, scheduler):
    model.train()
    total_loss = 0
    total_tokens = 0
    criterion = nn.CrossEntropyLoss(ignore_index=PAD_IDX)

    for encoder_input, encoder_mask, decoder_input, decoder_targets, _ in tqdm(train_loader):
        optimizer.zero_grad()
        encoder_input = encoder_input.to(DEVICE)
        encoder_mask = encoder_mask.to(DEVICE)
        decoder_input = decoder_input.to(DEVICE)
        decoder_targets = decoder_targets.to(DEVICE)

        logits = model(
            input_ids=encoder_input,
            attention_mask=encoder_mask,
            decoder_input_ids=decoder_input,
        )['logits']

        loss = criterion(logits.view(-1, logits.size(-1)), decoder_targets.view(-1))
        
        loss.backward()
        optimizer.step()
        if scheduler is not None: 
            scheduler.step()

        with torch.no_grad():
            num_tokens = torch.sum(decoder_targets != PAD_IDX).item()
            if num_tokens > 0:
                total_loss += loss.item() * num_tokens
                total_tokens += num_tokens

    return total_loss / total_tokens if total_tokens > 0 else 0
        
def eval_epoch(args, model, tokenizer, dev_loader, gt_sql_pth, model_sql_path, gt_record_path, model_record_path):
    model.eval()
    total_loss = 0
    total_tokens = 0
    criterion = nn.CrossEntropyLoss(ignore_index=PAD_IDX)
    
    generated_queries = []
    ground_truth_queries = []

    # *** FIX: Increased max_new_tokens to 256 and num_beams to 4 ***
    generation_config = GenerationConfig(
        max_new_tokens=256,
        pad_token_id=PAD_IDX,
        eos_token_id=tokenizer.eos_token_id,
        num_beams=4
    )

    with torch.no_grad():
        for encoder_input, encoder_mask, decoder_input, decoder_targets, gt_query_text in tqdm(dev_loader):
            encoder_input = encoder_input.to(DEVICE)
            encoder_mask = encoder_mask.to(DEVICE)
            decoder_input = decoder_input.to(DEVICE)
            decoder_targets = decoder_targets.to(DEVICE)
            
            # Loss calculation
            logits = model(
                input_ids=encoder_input,
                attention_mask=encoder_mask,
                decoder_input_ids=decoder_input,
            )['logits']

            loss = criterion(logits.view(-1, logits.size(-1)), decoder_targets.view(-1))
            num_tokens = torch.sum(decoder_targets != PAD_IDX).item()
            if num_tokens > 0:
                total_loss += loss.item() * num_tokens
                total_tokens += num_tokens
            
            # Generation
            generated_ids = model.generate(
                input_ids=encoder_input,
                attention_mask=encoder_mask,
                generation_config=generation_config
            )
            
            generated_sql = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
            
            # *** FIX: Apply SQL Cleaning ***
            cleaned_sql = [clean_sql_query(q) for q in generated_sql]
            
            generated_queries.extend(cleaned_sql)
            ground_truth_queries.extend(gt_query_text)
            
    # Save and compute
    save_queries_and_records(
        sql_queries=generated_queries,
        sql_path=model_sql_path,
        record_path=model_record_path
    )
    
    sql_em, record_em, record_f1, model_error_msgs = compute_metrics(
        gt_path=gt_sql_pth,
        model_path=model_sql_path,
        gt_query_records=gt_record_path,
        model_query_records=model_record_path
    )
    
    error_rate = sum(1 for msg in model_error_msgs if msg != "") / len(model_error_msgs)
    avg_loss = total_loss / total_tokens if total_tokens > 0 else 0
    
    return avg_loss, record_f1, record_em, sql_em, error_rate
        
def test_inference(args, model, tokenizer, test_loader, model_sql_path, model_record_path):
    model.eval()
    generated_queries = []
    
    # Same config as eval
    generation_config = GenerationConfig(
        max_new_tokens=256,
        pad_token_id=PAD_IDX,
        eos_token_id=tokenizer.eos_token_id,
        num_beams=4
    )

    with torch.no_grad():
        for encoder_input, encoder_mask, _, _, _ in tqdm(test_loader):
            encoder_input = encoder_input.to(DEVICE)
            encoder_mask = encoder_mask.to(DEVICE)
            
            generated_ids = model.generate(
                input_ids=encoder_input,
                attention_mask=encoder_mask,
                generation_config=generation_config
            )
            
            generated_sql = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
            
            # *** FIX: Apply SQL Cleaning ***
            cleaned_sql = [clean_sql_query(q) for q in generated_sql]
            generated_queries.extend(cleaned_sql)

    save_queries_and_records(
        sql_queries=generated_queries,
        sql_path=model_sql_path,
        record_path=model_record_path
    )
    print(f"Test queries saved to {model_sql_path}")
    print(f"Test records saved to {model_record_path}")

def main():
    args = get_args()
    if args.use_wandb:
        setup_wandb(args)

    # Load data
    train_loader, dev_loader, test_loader = load_t5_data(args.batch_size, args.test_batch_size)
    
    # Initialize model and tokenizer
    model, tokenizer = initialize_model(args)
    
    optimizer, scheduler = initialize_optimizer_and_scheduler(args, model, len(train_loader))

    # Train
    train(args, model, tokenizer, train_loader, dev_loader, optimizer, scheduler)

    # Final Evaluation
    print("Loading best model for final evaluation...")
    model = load_model_from_checkpoint(args, best=True)
    model.eval()
    
    # Dev set
    experiment_name = 'ft_experiment'
    model_type = 'ft' if args.finetune else 'scr'
    gt_sql_path = os.path.join(f'data/dev.sql')
    gt_record_path = os.path.join(f'records/ground_truth_dev.pkl')
    model_sql_path = os.path.join(f'results/t5_{model_type}_{experiment_name}_dev.sql')
    model_record_path = os.path.join(f'records/t5_{model_type}_{experiment_name}_dev.pkl')
    
    dev_loss, dev_record_f1, dev_record_em, dev_sql_em, dev_error_rate = eval_epoch(
        args, model, tokenizer, dev_loader,
        gt_sql_path, model_sql_path,
        gt_record_path, model_record_path
    )
    print(f"Final Dev Results: Loss: {dev_loss}, Record F1: {dev_record_f1}, Record EM: {dev_record_em}, SQL EM: {dev_sql_em}")
    print(f"Final Dev Results: {dev_error_rate*100:.2f}% of outputs led to SQL errors")

    # Test set
    model_sql_path = os.path.join(f'results/t5_{model_type}_{args.experiment_name}_test.sql')
    model_record_path = os.path.join(f'records/t5_{model_type}_{args.experiment_name}_test.pkl')
    test_inference(args, model, tokenizer, test_loader, model_sql_path, model_record_path)

if __name__ == "__main__":
    main()